/*
* constant for getting list of projects
* */


export const SOURCE_LIST_REQUEST = 'SOURCE_LIST_REQUEST';
export const SOURCE_LIST_SUCCESS = 'SOURCE_LIST_SUCCESS';
export const SOURCE_LIST_FAILURE = 'SOURCE_LIST_FAILURE';


export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST';
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS';
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE';

